#ifndef H5OUTPUTFILE_H
#define H5OUTPUTFILE_H

#include "h5filehelper.h"

/**
 * @brief The H5OutputFile class allows to manipulate the HDF5 files generated by
 *        MCPlusPlus
 */

class H5OutputFile : public H5FileHelper
{
public:
    H5OutputFile();

    virtual bool newFile(const char *fileName);
    void appendTransmittedExitPoints(const MCfloat *buffer, const hsize_t size);


private:
    bool createExitPointsDatasets();
};

#endif // H5OUTPUTFILE_H
